/**
 * ERR-02 (issue #19): logs never leak credentials, DB URLs or production
 * stacks; the correlation ID is generated by the server and follows its own
 * request only, so no caller can file its requests under another request's
 * ID; unknown errors become a safe INTERNAL failure; and a logging failure
 * can neither fail nor repeat a use case whose write already committed.
 */
import { IncomingMessage, ServerResponse } from 'node:http';
import { Socket } from 'node:net';
import { type AppResult, applicationError } from '@sheet-music/music-application';
import type { Request, Response } from 'express';
import { describe, expect, it, vi } from 'vitest';
import {
  type LoggerOptions,
  CORRELATION_HEADER,
  correlationMiddleware,
  createLogger,
  readClientCorrelationId,
  redactString,
  runUseCase,
  runWithRequestContext,
} from '../src/index';

const JWT =
  'eyJhbGciOiJFUzI1NiIsImtpZCI6ImtleS0xIn0.eyJzdWIiOiI2ZjFjMWE1MiIsInJvbGUiOiJhdXRoZW50aWNhdGVkIn0.c2lnbmF0dXJlLXNpZ25hdHVyZQ';
const SECRETS = [
  JWT,
  'opaque-refresh-7f3k',
  'hunter2',
  'pg-p4ss',
  'sb_secret_Zx81qLmN0pQr',
  'cookie-value-9',
  'q-token-55',
  'basic-dXNlcjpwYXNz',
];

function capture(options: Omit<LoggerOptions, 'write'> = {}) {
  const lines: string[] = [];
  const logger = createLogger({
    level: 'debug',
    production: true,
    ...options,
    write: (line) => lines.push(line),
  });
  const entries = () => lines.map((line) => JSON.parse(line) as Record<string, unknown>);
  return { logger, lines, entries };
}

describe('ERR-02 deep redaction', () => {
  it('removes credentials by field name and by value pattern, at any depth', () => {
    const { logger, lines, entries } = capture();

    logger.info('request.received', {
      scoreId: 'scr_1',
      request: {
        headers: {
          Authorization: `Bearer ${JWT}`,
          cookie: 'sb-session=cookie-value-9',
          'x-api-key': 'sb_secret_Zx81qLmN0pQr',
        },
        body: { refresh_token: 'opaque-refresh-7f3k', nested: [{ password: 'hunter2' }] },
      },
      config: { DATABASE_URL: 'postgres://app:pg-p4ss@db.internal:5432/scores' },
      note: `retrying postgres://app:pg-p4ss@db.internal/scores?sslmode=require with Bearer ${JWT}`,
      callback: 'https://app.example.test/cb?token=q-token-55&state=ok',
      upstream: 'Authorization: Basic basic-dXNlcjpwYXNz',
    });

    expect(lines).toHaveLength(1);
    for (const secret of SECRETS) {
      expect(lines[0]).not.toContain(secret);
    }
    const [entry] = entries();
    expect(entry).toMatchObject({
      level: 'info',
      event: 'request.received',
      scoreId: 'scr_1',
      request: {
        headers: { Authorization: '[REDACTED]', cookie: '[REDACTED]', 'x-api-key': '[REDACTED]' },
        body: { refresh_token: '[REDACTED]', nested: [{ password: '[REDACTED]' }] },
      },
      config: { DATABASE_URL: '[REDACTED]' },
      note: 'retrying postgres://[REDACTED]@db.internal/scores?sslmode=require with Bearer [REDACTED]',
      callback: 'https://app.example.test/cb?token=[REDACTED]&state=ok',
    });
  });

  it('logs errors with their cause chain, and with stacks outside production only', () => {
    const cause = new Error(
      'password authentication failed: postgres://app:pg-p4ss@db.internal/scores',
    );
    const error = new Error('score store unavailable', { cause });

    const production = capture({ production: true });
    production.logger.error('use_case.failed', { error });
    const development = capture({ production: false });
    development.logger.error('use_case.failed', { error });

    const [prodEntry] = production.entries();
    expect(prodEntry?.['error']).toEqual({
      name: 'Error',
      message: 'score store unavailable',
      cause: {
        name: 'Error',
        message: 'password authentication failed: postgres://[REDACTED]@db.internal/scores',
      },
    });
    expect(production.lines[0]).not.toContain('"stack"');
    const [devEntry] = development.entries();
    expect(devEntry).toMatchObject({ error: { stack: expect.stringContaining('at ') as unknown } });
    expect(development.lines[0]).not.toContain('pg-p4ss');
  });

  it.each([
    {
      name: 'a DB URL whose password contains a raw @',
      input: 'connect postgres://app:p@ss@db.example:5432/x failed',
      expected: 'connect postgres://[REDACTED]@db.example:5432/x failed',
    },
    {
      name: 'a libpq keyword DSN',
      input: 'host=db user=app password=hunter2 dbname=x',
      expected: 'host=db user=app password=[REDACTED] dbname=x',
    },
    {
      name: 'a libpq keyword DSN with a quoted password',
      input: "host=db password='hun ter2' sslpassword=k3y dbname=x",
      expected: 'host=db password=[REDACTED] sslpassword=[REDACTED] dbname=x',
    },
    {
      name: 'an ODBC-style connection string',
      input: 'Server=db;Uid=app;Pwd=hunter2;Database=x',
      expected: 'Server=db;Uid=app;Pwd=[REDACTED];Database=x',
    },
    {
      name: 'JSON with credential members, serialized into a string',
      input: '{"password":"hunter2","refresh_token": "r-123","code":"NOT_FOUND"}',
      expected: '{"password":"[REDACTED]","refresh_token": "[REDACTED]","code":"NOT_FOUND"}',
    },
    {
      name: 'an OAuth authorization code in a callback URL',
      input: 'https://x.test/cb?code=authcode123&state=s',
      expected: 'https://x.test/cb?code=[REDACTED]&state=s',
    },
    {
      name: 'diagnostics that only look like pairs',
      input: 'SQLSTATE code=23505 at offset=12, sslmode=require, role=authenticated',
      expected: 'SQLSTATE code=23505 at offset=12, sslmode=require, role=authenticated',
    },
  ])('masks $name inside a string', ({ input, expected }) => {
    expect(redactString(input)).toBe(expected);
  });

  it('never throws, even for a field that cannot be read', () => {
    const { logger, entries } = capture();
    const hostile = {
      get boom(): never {
        throw new Error('getter exploded');
      },
    };
    const cyclic: Record<string, unknown> = { name: 'loop' };
    cyclic['self'] = cyclic;

    expect(() => logger.warn('odd.fields', { hostile, cyclic, big: 10n })).not.toThrow();
    expect(entries()).toEqual([
      expect.objectContaining({ level: 'warn', event: 'log.unserializable' }),
    ]);
  });
});

describe('ERR-02 correlation follows its own request', () => {
  it('keeps each concurrent request on its own correlation ID', async () => {
    const { logger, entries } = capture();
    const request = (correlationId: string, delays: readonly number[]) =>
      runWithRequestContext({ correlationId }, async () => {
        for (const [step, delay] of delays.entries()) {
          await new Promise((resolve) => setTimeout(resolve, delay));
          logger.info('step', { owner: correlationId.slice(0, 1), step });
        }
      });

    await Promise.all([request('a-request-0001', [5, 0, 5]), request('b-request-0002', [0, 5, 0])]);
    logger.info('outside');

    const logged = entries();
    expect(logged).toHaveLength(7);
    for (const entry of logged.slice(0, 6)) {
      expect(entry['correlationId']).toBe(
        entry['owner'] === 'a' ? 'a-request-0001' : 'b-request-0002',
      );
    }
    expect(logged[6]).not.toHaveProperty('correlationId');
  });

  it.each([
    { name: 'a UUID', incoming: '2b1f8f0e-5a44-4f55-9b1e-4a1c2f3e4d5a', kept: true },
    { name: 'an 8-character ID', incoming: 'abcd-123', kept: true },
    { name: 'a 7-character ID', incoming: 'abc-123', kept: false },
    { name: 'a 65-character ID', incoming: 'a'.repeat(65), kept: false },
    { name: 'a log-forging newline', incoming: 'abcd1234\n{"level":"error"}', kept: false },
    { name: 'a quote', incoming: 'abcd1234"x', kept: false },
    { name: 'a repeated header', incoming: ['abcd-1234', 'efgh-5678'], kept: false },
    { name: 'no header', incoming: undefined, kept: false },
  ])('a client correlation ID that is $name is kept for logs: $kept', ({ incoming, kept }) => {
    expect(readClientCorrelationId(incoming)).toBe(kept ? incoming : undefined);
  });

  it("never adopts a client's ID: two requests replaying one victim's ID get their own", () => {
    const { logger, entries } = capture();
    const middleware = correlationMiddleware();
    const victimId = '2b1f8f0e-5a44-4f55-9b1e-4a1c2f3e4d5a';
    const served = [victimId, victimId].map(() => {
      const req = new IncomingMessage(new Socket());
      req.headers = { [CORRELATION_HEADER]: victimId };
      const res = new ServerResponse(req);
      middleware(req as unknown as Request, res as unknown as Response, () => {
        logger.info('handled');
      });
      return res.getHeader(CORRELATION_HEADER);
    });

    const [first, second] = served;
    expect(first).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    expect(second).not.toBe(first);
    expect(served).not.toContain(victimId);
    expect(
      entries().map(({ correlationId, clientCorrelationId }) => ({
        correlationId,
        clientCorrelationId,
      })),
    ).toEqual([
      { correlationId: first, clientCorrelationId: victimId },
      { correlationId: second, clientCorrelationId: victimId },
    ]);
  });

  it('keeps the context fields out of reach of logged fields', () => {
    const { logger, entries } = capture();
    runWithRequestContext({ correlationId: 'server-id-0001' }, () =>
      logger.info('forged', { correlationId: 'forged-0001', clientCorrelationId: 'forged-0002' }),
    );

    expect(entries()).toEqual([expect.objectContaining({ correlationId: 'server-id-0001' })]);
    expect(entries()[0]).not.toHaveProperty('clientCorrelationId');
  });
});

describe('ERR-02 use-case execution', () => {
  it('turns a thrown value into a safe INTERNAL failure and logs it redacted', async () => {
    const { logger, lines } = capture();

    const result = await runUseCase(logger, 'create_score', () =>
      Promise.reject(new Error('insert failed for postgres://app:pg-p4ss@db.internal/scores')),
    );

    expect(result.ok).toBe(false);
    expect(
      result.ok ? undefined : { code: result.error.code, message: result.error.message },
    ).toEqual({
      code: 'INTERNAL',
      message: 'An internal error occurred.',
    });
    expect(lines).toHaveLength(1);
    expect(lines[0]).toContain('use_case.threw');
    expect(lines[0]).not.toContain('pg-p4ss');
  });

  it('returns a committed result exactly once when the log output fails', async () => {
    const logger = createLogger({
      write: () => {
        throw new Error('stdout closed');
      },
    });
    const committed: AppResult<{ revision: number }> = { ok: true, value: { revision: 2 } };
    const execute = vi.fn(() => Promise.resolve(committed));

    const result = await runUseCase(logger, 'edit_score', execute);

    expect(result).toBe(committed);
    expect(execute).toHaveBeenCalledTimes(1);
  });

  it('passes an expected failure through unchanged when the log output fails', async () => {
    const logger = createLogger({
      write: () => {
        throw new Error('stdout closed');
      },
    });
    const failure: AppResult<never> = {
      ok: false,
      error: applicationError('DEPENDENCY_UNAVAILABLE', [], undefined, new Error('pool exhausted')),
    };
    const execute = vi.fn(() => Promise.resolve(failure));

    await expect(runUseCase(logger, 'save_score', execute)).resolves.toBe(failure);
    expect(execute).toHaveBeenCalledTimes(1);
  });
});
