/**
 * Per-request context (issue #19): a server-generated correlation ID carried
 * by AsyncLocalStorage from the first middleware to every log line and error
 * envelope of the same request. Each request runs in its own store, so
 * concurrent requests (of the same or of different users) never see each
 * other's context. Nothing global is mutated.
 */
import { AsyncLocalStorage } from 'node:async_hooks';
import { randomUUID } from 'node:crypto';
import type { RequestHandler } from 'express';

export interface RequestContext {
  /** Generated by this server for every request; never taken from the client. */
  readonly correlationId: string;
  /** A valid `x-correlation-id` sent by the client, kept as a separate log field only. */
  readonly clientCorrelationId?: string;
}

/** Request header a client may use to label its request, and response header carrying our ID. */
export const CORRELATION_HEADER = 'x-correlation-id';

/**
 * A client-supplied correlation ID is kept (for logs) only when it is one
 * value of 8-64 letters, digits, `.`, `_`, `:` or `-` (for example a UUID):
 * bounded, and safe to write into a log line.
 */
const CLIENT_CORRELATION_ID = /^[A-Za-z0-9._:-]{8,64}$/;

const storage = new AsyncLocalStorage<RequestContext>();

/** The client's correlation ID if it is one valid value, otherwise undefined. */
export function readClientCorrelationId(
  incoming: string | readonly string[] | undefined,
): string | undefined {
  return typeof incoming === 'string' && CLIENT_CORRELATION_ID.test(incoming)
    ? incoming
    : undefined;
}

export function runWithRequestContext<T>(context: RequestContext, run: () => T): T {
  return storage.run(Object.freeze({ ...context }), run);
}

/** The context of the request being served, or undefined outside a request. */
export function currentRequestContext(): RequestContext | undefined {
  return storage.getStore();
}

/**
 * First middleware of each app: generates the request's correlation ID,
 * echoes it in the response header and runs the rest of the request inside
 * its context. The ID is always generated here: a caller cannot choose it,
 * so it cannot file its requests under another request's (or another user's)
 * ID. A valid client-supplied ID is kept as `clientCorrelationId`, which the
 * logger writes as a separate field.
 */
export function correlationMiddleware(): RequestHandler {
  return (req, res, next) => {
    const correlationId = randomUUID();
    const clientCorrelationId = readClientCorrelationId(req.headers[CORRELATION_HEADER]);
    res.setHeader(CORRELATION_HEADER, correlationId);
    runWithRequestContext(
      clientCorrelationId === undefined
        ? { correlationId }
        : { correlationId, clientCorrelationId },
      () => next(),
    );
  };
}
