/**
 * @sheet-music/music-domain
 *
 * Canonical ScoreSpec v1 contract, invariants and pure music logic (ADR-001,
 * ADR-002). Semantics: docs/architecture/SCORESPEC_V1_SEMANTICS.md.
 */
export { validateScoreSpec } from './validate';
export {
  type BarContent,
  type Interval,
  type ScoreEdit,
  type ScoreEditInput,
  type ScoreOperation,
  type ScoreOperationInput,
  type ScoreOperationType,
  type TransposeTarget,
  OPERATION_LIMITS,
  SCORE_OPERATION_TYPES,
  applyScoreEdit,
  barContentSchema,
  chooseInterval,
  scoreEditSchema,
  scoreOperationSchema,
  transposePitch,
  transposePitchClass,
} from './operations';
export {
  type Annotation,
  type Articulation,
  type ChordEvent,
  type ChordNote,
  type ChordSymbol,
  type Clef,
  type Duration,
  type DurationValue,
  type DynamicEvent,
  type DynamicMark,
  type Fingering,
  type Hand,
  type HarmonicAnalysis,
  type HarmonyEvent,
  type KeySignature,
  type Measure,
  type MeasureKind,
  type MusicalEvent,
  type NoteEvent,
  type PedalEvent,
  type Pitch,
  type PitchClass,
  type PlaybackFeel,
  type RestEvent,
  type ScaleDegreeLabel,
  type ScoreSpec,
  type ScoreSpecInput,
  type Slur,
  type Staff,
  type Step,
  type Tempo,
  type Tie,
  type TimeSignature,
  type TonalContext,
  type Tuplet,
  type Voice,
  ID_PATTERN,
  scoreSpecSchema,
} from './schema';
export {
  type DomainError,
  type DomainErrorCode,
  type DomainErrorDetail,
  type DomainErrorDetailCode,
  type ErrorPath,
  type LimitDetailCode,
  type OperationDetailCode,
  type Result,
  type ValidationDetailCode,
  DOMAIN_ERROR_CODES,
  LIMIT_DETAIL_CODES,
  OPERATION_DETAIL_CODES,
  VALIDATION_DETAIL_CODES,
  domainError,
  errorDetail,
  isLimitDetailCode,
} from './errors';
export { MVP_LIMITS, type MvpLimits } from './limits';
export {
  type Fraction,
  ZERO,
  addFractions,
  compareFractions,
  divideFractions,
  formatFraction,
  fraction,
  fractionsEqual,
  multiplyFractions,
  reduce,
  subtractFractions,
  sumFractions,
} from './rational';
export {
  barDuration,
  durationToFraction,
  effectiveTimeSignature,
  meterDuration,
  writtenDuration,
} from './duration';
export {
  PIANO_KEY_RANGE,
  formatWrittenPitch,
  isOnPianoKeyboard,
  writtenPitchToKey,
  writtenPitchesEqual,
} from './pitch';
export { canonicalizeColor } from './color';
export { type DeepReadonly, deepFreeze } from './deep-freeze';
export {
  type BarInfo,
  type DuplicateIdOccurrence,
  type EntityKind,
  type EventLocation,
  type IndexedEntity,
  type IndexedEvent,
  type LayerKind,
  type NoteTarget,
  type ScoreIndex,
  type TiePair,
  type TupletGroup,
  buildScoreIndex,
} from './score-index';
